# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('userid', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('blood_units', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('userid', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('blood_type', models.CharField(choices=[('A+', 'a+'), ('B+', 'b+')], max_length=3)),
                ('age', models.IntegerField()),
                ('weight', models.FloatField()),
                ('haemo', models.FloatField()),
                ('last_donation', models.DateTimeField()),
            ],
        ),
    ]
