# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uwhapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodbank',
            name='id',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='id',
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='userid',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donor',
            name='userid',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
