# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 16:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uwhapp', '0002_auto_20170715_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='donor',
        ),
        migrations.RenameField(
            model_name='requesttodonor',
            old_name='requestee_name',
            new_name='requestee',
        ),
        migrations.RemoveField(
            model_name='donorhistory',
            name='last_donation',
        ),
        migrations.AddField(
            model_name='donor',
            name='last_donation',
            field=models.DateField(default=datetime.datetime(2017, 7, 15, 16, 4, 16, 828081)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donorhistory',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 7, 15, 16, 4, 45, 730223)),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
