# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uwhapp', '0002_auto_20170715_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=100)),
                ('request_units', models.IntegerField()),
                ('blood_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uwhapp.BloodBank')),
            ],
        ),
    ]
