# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uwhapp', '0003_auto_20170715_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbank',
            name='latitude',
            field=models.CharField(default=0.0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='longitude',
            field=models.CharField(default=0.0, max_length=20),
            preserve_default=False,
        ),
    ]
