# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uwhapp', '0004_auto_20170715_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbank',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
